name: FounnPlugin
main: de.founntain.founnplugin.FounnPlugin
version: 1.0
api-version: 1.16
commands:
   menu:
      description: Opens the server menu
      usage: /menu
   coords:
      description: Tells everyone your coords
      usage: /coords
   back:
      description: Tps you to your last before teleport location
      usage: /back
   deathCoord:
      description: Tps you on your death position
      usage: /deathCoord
   sendItem:
      description: Sends items to a given player
      usage: /back
   spawnCustomMob:
      description: Spawns a custom mob
      usage: /spawnCustomMob
   deathBox:
      description: Opens your deathbox
      usage: /deathBox
   clearInv:
      description: Clears your inventory
      usage: /clearInv
   day:
      description: Makes day
      usage: /day
   spawn:
      description: Teleports you to your spawnpoint. If you not slept in a bed yet, world spawn is used
      usage: /spawn
   w:
      description: Change the weater c => clear, r => rain, t => thunder
      usage: /w
   chunkScan:
      description: Scans the chunk for minerals and other blocks
      usage: /chunkScan
   world:
      description: Opens a list of all maps.
      usage: /world
   test:
      description: SUCK MY DICk fuck u
      usage: /test